### ISSUE TITLE
How to connect firestore database with google datastudio ?

### ISSUE THREAD

**Issue by AwalDeep** [google/datastudio#13]

**Comment by bencochrane1** [comment]
Looks like sending firestore data to BigQuery then using Data Studio to get data from BigQuery is a potential solution here https://www.en.advertisercommunity.com/t5/Data-Studio/Firebase-and-Firestore/td-p/1237071#

**Comment by minhaz** [comment]
You can create your own community connector from using the [Cloud Firestore REST API](https://firebase.google.com/docs/firestore/use-rest-api).
